### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by blagh**
Well hello! Just here to update some dependencies.

Mostly straightforward, only other changes are in tests due to some reorganization inside scalatest.

### CODE REVIEW

**Review by dvgica — APPROVED** [review]
OHAI! Thanks for this! I should probably setup CI on the repo but I assume you've run through everything already.

**Comment by dvgica** [comment]
That said, I don't think this is going to be published anywhere. I obviously don't have access to the PD Artifactory any longer. I would happily give you admin access to the repo if you wanted to work on getting it published to Sonatype via GitHub actions or something....

**Comment by dvgica** [comment]
Although I think you should be able to manually publish to the PD ~Artifactory~ Bintray from your local machine too? Not a great long-term solution but it would work for now.

**Comment by blagh** [comment]
Re: manual publish: probably? 😆 If not, maybe I'll see if I can make a PagerDuty fork for that

**Comment by blagh** [comment]
🤦‍♀️ just realized i forgot to try the integration tests -- PR incoming :sweat:

**Comment by dvgica** [comment]
:+1: bump the patch version while you're at it :-)

**Pull request merged**
